[dependencies]
base = "0.11.1"
xtended-numbers = "0.3.1"

[package]
name = "candid"
version = "1.1.1"
description = "A Candid library for encoding and decoding candid bytes"
repository = "https://github.com/edjcase/motoko_candid"
keywords = [ "candid" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"
