[package]
name = "candid"
version = "2.4.1"
description = "A Candid library for encoding and decoding candid bytes"
repository = "https://github.com/edjcase/motoko_candid"
keywords = ["candid", "encode", "decode", "idl"]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"xtended-numbers@2" = "2.3.0"
"buffer@0" = "0.1.0"

[dev-dependencies]
test = "2.1.1"
